# Generated by Django 3.2.7 on 2021-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, verbose_name='사용자 아이디')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='업로드시간')),
                ('image', models.ImageField(upload_to='image/', verbose_name='image')),
                ('labeling', models.BooleanField(default=False, verbose_name='라벨링 여부')),
                ('labeling_name', models.CharField(max_length=100, verbose_name='라벨링명')),
            ],
        ),
    ]
