# Generated by Django 3.2.7 on 2021-11-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='모델 파일 이름')),
                ('model', models.FileField(upload_to='image/', verbose_name='파일 경로')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='파일 생성 시간')),
                ('data_size', models.IntegerField()),
                ('accuracy', models.CharField(max_length=10, verbose_name='정확도')),
                ('learning_time', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='User')),
            ],
        ),
    ]
