# Generated by Django 3.2.7 on 2021-10-05 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='이미지명'),
            preserve_default=False,
        ),
    ]
